title = "Jakamisen periaate pelastaa maailman"
baseURL = "https://share.fi"
uglyurls = false

timeZone = "Europe/Helsinki"
languageCode = "fi-fi"
DefaultContentLanguage = "fi"
theme = "classless"

[outputs]
   home = [ "HTML", "JSON" ]

[menu]


 [[menu.secondary]]
  pre = ""
  name   = "Aihealueet"
  url    = "/aihealueet/"
  weight = 50

[permalinks]
  post = ":slug/"

[taxonomies]
  tag = "avainsanat"
  category = "aihealueet"
  archive = "arkistot"
  

  dateFormat = "02.01.2006"
  

SectionPagesMenu = "main"
pluralizelisttitles = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

PaginatePath = "sivu"
disableKinds = ["RSS"]



[params]

favicon = "https://sharefi.sirv.com/static/favicon.ico"

show_summaries = true

description = "Maailmanopettaja Maitreya odottaa kutsua voidakseen laajasti tulla julkisuuteen. Hänet tunnetaan myös nimillä Kristus, Maitreya Buddha, Imam Mahdi, Messias riippuen uskontokunnasta."

#Parametrin nimi = luokan nimi CSS:ssä, eli css-luokkanimi on sama!
#sivustonjuuri # .sivustonjuuri
################################ TÄYTÄ NÄMÄ
#käytetään siellä missä omistajan nimi ilmenee
  sivustonomistaja = "Share.fi"
  sivustonomistajapiste  = "Share.fi."
#käytetään siellä missä omistajan nimi ilmenee genetiivimuodossa, kuten valikossa"Sivusto on omistajan"
  sivustonomistajagenetiivi = "Share.fi:n"
  sivustonomistajagenetiivipiste = "Share.fi:n."
#käytetään siellä missä omistajan nimi ilmenee illatiivimuodossa, kuten yhteydenottosivulla "Ota yhteyttä omistajaan"
  sivustonomistajaillatiivi = "Share.fi:hin"
  sivustonomistajaillatiivipiste = "Share.fi:hin."
# käytetään omistajan nimen tarkenteena, selitteenä mm. tietosuojalausekkeessa
  sivustonomistajatarkenne = "Tämä on share.fi kotisivu."
# Jos halutaan jokin teksti jokaiselle alasivulle ylös vasemmalle
  paivanviesti = ">Päivän viesti"
# Copyright-teksti Tämä teksti tulee alatunnisteeseen klikattavaksi ja johtaa etusivulle. 
  alatunnistecopyright = "Share.fi, meidän sivustomme"
  